keyvault:
  use_key_vault: true
  name: policyweaverajr
  authentication_method: azure_cli
fabric:
  mirror_id: 843c4569-9e72-4cb0-b133-517480633567
  mirror_name: unitycatalogdbxsweden
  workspace_id: 9d55abae-f66a-428d-acb1-aeb34797207c
  tenant_id: 349e9766-d222-4645-9d31-c2036c7e2885
  fabric_role_suffix: PW
  fabric_role_prefix: PW
  delete_default_reader_role: true
  policy_mapping: role_based
service_principal:
  client_id: service-principal-client-id
  client_secret: service-principal-client-secret
  tenant_id: service-principal-tenant-id
source:
  name: DEMODATA
type: SNOWFLAKE
# databricks:
#   workspace_url: https://adb-xxxxxxxxxxx.azuredatabricks.net/
#   account_id: <your databricks account id>
#   account_api_token: <Depending on the keyvault setting: the keyvault secret name or your databricks secret> 
snowflake:
  account_name: KWMPJES-TG64607
  user_name: policyweaver
  password: databricksRocks123
  warehouse: COMPUTE_WH