fabric:
  mirror_id: <your fabric mirrored item id>
  mirror_name: <your fabric mirrored item name>
  workspace_id: <your fabric workspace id>
  tenant_id: <your fabric tenant id>
  fabric_role_suffix: PWPolicy
  delete_default_reader_role: true
service_principal:
  client_id: <your azure SP client id>
  client_secret: <your azure SP secret>
  tenant_id: <your azure tenant id again>
source:
  name: <your databricks catalog name as named in Azure Databricks>
type: UNITY_CATALOG
databricks:
  workspace_url: https://adb-xxxxxxxxxxx.azuredatabricks.net/
  account_id: <your databricks account id>
  account_api_token: <your databricks secret> 
