fabric:
  mirror_id: <<your_fabric_mirror_item_id>
  mirror_name: main
  workspace_id: <your_fabric_workspace_id>
  tenant_id: <your_fabric_tenant_id>
service_principal:
  client_id: <your_azure_sp_client_id>
  client_secret: <your_azure_sp_secret_id>
  tenant_id: <your_azure_tenant_id>
source:
  name: main
  # schemas:
  # - name: default
  #   tables:
  #   - churn
type: UNITY_CATALOG
workspace_url: https://adb-2482044815297001.1.azuredatabricks.net/
